
---
title: "Week 10: Statistical analysis of areal data"
output: github_document
---

```{r global_options, eval=T, echo=F,results='hide', error=F, warning=FALSE}

knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.path='Figs/',  warning=FALSE, message=FALSE, results='hide')
rm(list=ls())
library(spdep)
library(rgdal)
library(maptools)
library(RColorBrewer)
```

# Areal Data and Spatial Autocorrelation

```{r area1, eval=T, echo=T}

NY8 <- readOGR("Data", "NY8_utm18")
TCE <- readOGR("Data", "TCE")
cities <- readOGR("Data", "NY8cities")

par(mfrow=c(1,2))
plot(NY8, border="grey60", axes=TRUE)
text(coordinates(cities), labels=as.character(cities$names), font=2, cex=0.9)
text(bbox(NY8)[1,1], bbox(NY8)[2,2], labels="a)", cex=0.8)

plot(NY8, border="grey60", axes=TRUE)
points(TCE, pch=1, cex=0.7)
points(TCE, pch=3, cex=0.7)
text(coordinates(TCE), labels=as.character(TCE$name), cex=0.7,
 font=1, pos=c(4,1,4,1,4,4,4,2,3,4,2), offset=0.3)
text(bbox(NY8)[1,1], bbox(NY8)[2,2], labels="b)", cex=0.8)

# Syracuse 

Syracuse <- NY8[NY8$AREANAME == "Syracuse city",]
plot(Syracuse)

# creating conginuity neighours

Sy0_nb=poly2nb(Syracuse, queen=T)
Sy1_nb=poly2nb(Syracuse, queen=F)

# creating distance-based neighours

coords <- coordinates(Syracuse)
IDs <- row.names(Syracuse)
Sy8_nb <- knn2nb(knearneigh(coords, k=1), row.names=IDs)
Sy9_nb <- knn2nb(knearneigh(coords, k=2), row.names=IDs)
Sy10_nb <- knn2nb(knearneigh(coords, k=4), row.names=IDs)
dsts <- unlist(nbdists(Sy8_nb, coords))
Sy11_nb <- dnearneigh(coords, d1=0, d2=0.75*max(dsts), row.names=IDs)


# Spatial weights 

# Weights have different style, e.g., 'W' row-standarized weights, 'B' binary

Sy0_lw_W <- nb2listw(Sy0_nb)
Sy0_lw_W
names(Sy0_lw_W)


#1/rev(range(card(Sy0_lw_W$neighbours)))
unlist(Sy0_lw_W$weights)
sapply(Sy0_lw_W$weights, sum)


Sy0_lw_B <- nb2listw(Sy0_nb, style="B")
summary(unlist(Sy0_lw_B$weights))
summary(sapply(Sy0_lw_B$weights, sum))

# define weight based on distance

dsts <- nbdists(Sy0_nb, coordinates(Syracuse))
idw <- lapply(dsts, function(x) 1/(x/1000))
Sy0_lw_idwB <- nb2listw(Sy0_nb, glist=idw, style="B")
summary(unlist(Sy0_lw_idwB$weights))
summary(sapply(Sy0_lw_idwB$weights, sum))

# Allow all-zeros neighourhood, the folling line will output errors,
# but with zero.polic=T, the error will be gone.
#
#try(Sy0_lw_D1 <- nb2listw(Sy11_nb, style="B"))
#
#Sy0_lw_D1 <- nb2listw(Sy11_nb, style="B", zero.policy=TRUE)
#print(Sy0_lw_D1, zero.policy=TRUE)


# Importing the specificition of spatial neighbours and weights generated by GeoDa

NY_nb <- read.gal("Data/NY_nb.gal", region.id=row.names(NY8))

# Using Weights to Simulate Spatial Autocorrelation

set.seed(987654)
n <- length(Sy0_nb)
uncorr_x <- rnorm(n)
rho <- 0.5
# (I-\rho*w)
autocorr_x <- invIrW(Sy0_lw_W, rho) %*% uncorr_x


oopar <- par(mfrow=c(1,2), mar=c(4,4,3,2)+0.1)
plot(uncorr_x, lag(Sy0_lw_W, uncorr_x), xlab="", cex.lab=0.8,
 ylab="spatial lag", main="Uncorrelated random variable", cex.main=0.8)
lines(lowess(uncorr_x, lag(Sy0_lw_W, uncorr_x)), lty=2, lwd=2)

plot(autocorr_x, lag(Sy0_lw_W, autocorr_x),
 xlab="", ylab="",
 main="Autocorrelated random variable", cex.main=0.8, cex.lab=0.8)
lines(lowess(autocorr_x, lag(Sy0_lw_W, autocorr_x)), lty=2, lwd=2)
par(oopar)

# Spatial Autocorrelation: Tests

moran.test(uncorr_x, listw=Sy0_lw_W)
moran.test(autocorr_x, listw=Sy0_lw_W)
moran.test(autocorr_x, listw=nb2listw(Sy9_nb, style="W"))


# Moran's I plot 

library(RColorBrewer)
oopar <- par(mfrow=c(1,2))
msp <- moran.plot(NY8$Cases, listw=nb2listw(NY_nb, style="C"), quiet=TRUE)
title("Moran scatterplot")

infl <- apply(msp$is.inf, 1, any)
x <- NY8$Cases
lhx <- cut(x, breaks=c(min(x), mean(x), max(x)), labels=c("L", "H"), include.lowest=TRUE)
wx <- lag(nb2listw(NY_nb, style="C"), NY8$Cases)
lhwx <- cut(wx, breaks=c(min(wx), mean(wx), max(wx)), labels=c("L", "H"), include.lowest=TRUE)
lhlh <- interaction(lhx, lhwx, infl, drop=TRUE)
cols <- rep(1, length(lhlh))
cols[lhlh == "H.L.TRUE"] <- 2
cols[lhlh == "L.H.TRUE"] <- 3
cols[lhlh == "H.H.TRUE"] <- 4
plot(NY8, col=brewer.pal(4, "Accent")[cols])
legend("topright", legend=c("None", "HL", "LH", "HH"), fill=brewer.pal(4, "Accent"), bty="n", cex=0.8, y.intersp=0.8)
title("Tracts with influence")
par(oopar)

## Local test

lm1 <- localmoran(NY8$Cases, listw=nb2listw(NY_nb, style="C"))
#lm2 <- as.data.frame(localmoran.sad(lm(Cases ~ 1, NY8), nb=NY_nb, style="C"))
#lm3 <- as.data.frame(localmoran.exact(lm(Cases ~ 1, NY8), nb=NY_nb, style="C"))

NY8$Standard <- lm1[,1]

spplot(NY8, c("Standard"), at=c(-2.5,-1.4,-0.6,-0.2,0,0.2,0.6,4,7), col.regions=colorRampPalette(gry)(8))

# Local test for rate
#r <- sum(NY8$Cases)/sum(NY8$POP8)
#rni <- r*NY8$POP8
#lw <- nb2listw(NY_nb, style="C")
#sdCR <- (NY8$Cases - rni)/sqrt(rni)
#wsdCR <- lag(lw, sdCR)
#I_CR <- sdCR * wsdCR
#
#gry <- c(rev(brewer.pal(8, "Reds")[1:6]), brewer.pal(6, "Blues"))
#NY8$Standard <- lm1[,1]
#NY8$"Constant_risk" <- I_CR
##nms <- match(c("Standard", "Constant_risk"), names(NY8))
#spplot(NY8, c("Standard", "Constant_risk"), at=c(-2.5,-1.4,-0.6,-0.2,0,0.2,0.6,4,7), col.regions=colorRampPalette(gry)(8))

```



```
